### ISSUE TITLE
Response headers filtering: multi-value header values are dropped

### ISSUE THREAD

**Issue by thePanz** [redirectionio/fastly-worker#6]
Response headers can be added multiple times by the server, in particular the `Cookie` and `Vary` header (see: https://www.rfc-editor.org/rfc/rfc7230#section-3.2.2)

Currently the application.rs part handling response's headers is only fetching the first value, thus discarding all other values.
This results in headers being dropped, even if there are no rules in place.

The issue rely on https://github.com/redirectionio/fastly-worker/blob/master/src/rio/application.rs#L207 where `request.get_header()`, is used instead of `request.get_header_all()`.
The subsequent handling should be adapted too, as to push and append the original set of headers, including the multi-value ones.

**Comment by lyrixx** [comment]
Hello, 

Do you want to give it a try and submit a PR?.if you can't, this is perfectly fine, I'll do it 👍🏼

**Comment by lyrixx** [comment]
@thePanz so it looks like the issue comes from fastly?

**Comment by lyrixx** [comment]
> * collecting (only) the first value for each header

`response.get_header_names()` returns only the first header?

**Comment by thePanz** [comment]
IIRC `response.get_header_names()` get the names, but the values can be multiple (for Vary and Cookie for example).

> The issue rely on https://github.com/redirectionio/fastly-worker/blob/master/src/rio/application.rs#L207 where request.get_header(), is used instead of request.get_header_all().
> The subsequent handling should be adapted too, as to push and append the original set of headers, including the multi-value ones.

**Comment by xavierlacot** [comment]
fixed in https://github.com/redirectionio/fastly-worker/commit/d445ff7d4d3cb80f0835941974612fb7bd878efd
